steps:
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "asia-southeast2-docker.pkg.dev/peduli-ternak/node-api-repo/node-api",
        ".",
      ]
  # Push the container image to Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "asia-southeast2-docker.pkg.dev/peduli-ternak/node-api-repo/node-api",
      ]
  # Deploy container image to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      [
        "run",
        "deploy",
        "node-api",
        "--image",
        "asia-southeast2-docker.pkg.dev/peduli-ternak/node-api-repo/node-api",
        "--region",
        "asia-southeast2",
        "--allow-unauthenticated",
        "--min-instances",
        "0",
        "--max-instances",
        "3",
      ]
images: ["asia-southeast2-docker.pkg.dev/peduli-ternak/node-api-repo/node-api"]
